# Generated by Django 4.1.6 on 2023-04-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_review_rslug_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rslug',
        ),
    ]
